<a href="https://colab.research.google.com/github/shubhamgautam1211/Machine-Learning-Standalone/blob/main/SG_17_RandomForest_NewsPopularity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn import datasets 
from sklearn.tree import DecisionTreeClassifier 
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import median_absolute_error
from sklearn.metrics import mean_squared_log_error
from sklearn.metrics import max_error
from sklearn.metrics import explained_variance_score
from sklearn.metrics import r2_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error

In [ ]:
data = pd.read_csv('OnlineNewsPopularity.csv')

data.head()

                                                 url  ...   shares
0  http://mashable.com/2013/01/07/amazon-instant-...  ...      593
1  http://mashable.com/2013/01/07/ap-samsung-spon...  ...      711
2  http://mashable.com/2013/01/07/apple-40-billio...  ...     1500
3  http://mashable.com/2013/01/07/astronaut-notre...  ...     1200
4   http://mashable.com/2013/01/07/att-u-verse-apps/  ...      505

[5 rows x 61 columns]

**Remove unwanted features such as url, timedelta**

In [ ]:
data = data.drop(['url', ' timedelta'], axis=1)
data.head()

    n_tokens_title   n_tokens_content  ...   abs_title_sentiment_polarity   shares
0             12.0              219.0  ...                       0.187500      593
1              9.0              255.0  ...                       0.000000      711
2              9.0              211.0  ...                       0.000000     1500
3              9.0              531.0  ...                       0.000000     1200
4             13.0             1072.0  ...                       0.136364      505

[5 rows x 59 columns]

In [ ]:
cols=data.columns

#X = data.drop([' shares'],axis=1) 
#y = data[' shares']

X = data.loc[:, data.columns != ' shares']
y = data.loc[:, data.columns == ' shares']

**Perform range normalization on numerical features not in the range of** 
**0 to 1**

In [ ]:
from sklearn.preprocessing import MinMaxScaler
cols=cols.drop([' shares'])
scaler = MinMaxScaler()
X=pd.DataFrame(scaler.fit_transform(X),columns=cols)

In [ ]:
X.head()

    n_tokens_title  ...   abs_title_sentiment_polarity
0         0.476190  ...                       0.187500
1         0.333333  ...                       0.000000
2         0.333333  ...                       0.000000
3         0.333333  ...                       0.000000
4         0.523810  ...                       0.136364

[5 rows x 58 columns]

In [ ]:
X.describe()

        n_tokens_title  ...   abs_title_sentiment_polarity
count     39644.000000  ...                   39644.000000
mean          0.399940  ...                       0.156064
std           0.100668  ...                       0.226294
min           0.000000  ...                       0.000000
25%           0.333333  ...                       0.000000
50%           0.380952  ...                       0.000000
75%           0.476190  ...                       0.250000
max           1.000000  ...                       1.000000

[8 rows x 58 columns]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [ ]:
X_shape = X_train.shape
y_shape = y_train.shape

print(f'X_train: Shape-{X_shape}')
print(f'y_train: Shape-{y_shape}')

X_shape = X_test.shape
y_shape = y_test.shape

print(f'X_test: Shape-{X_shape}')
print(f'y_test: Shape-{y_shape}')

X_train: Shape-(27750, 58)
y_train: Shape-(27750, 1)
X_test: Shape-(11894, 58)
y_test: Shape-(11894, 1)

## **Random Forest Modelling**

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model=RandomForestRegressor()
model.fit(X_train,y_train.values.ravel())
y_pred=model.predict(X_test)

In [ ]:
mse = mean_squared_error(y_test,y_pred)
print("MSE:",mse)

print("----------------------------------------------")

mae = mean_absolute_error(y_test, y_pred)
print("Mean absolute error: ",mae)

print("----------------------------------------------")

MAE = median_absolute_error(y_test, y_pred)
print("Median absolute error: ",MAE)

print("----------------------------------------------")

msle = mean_squared_log_error(y_test, y_pred)
print("Mean squared logarithmic error: ",msle)

print("----------------------------------------------")

me = max_error(y_test, y_pred)
print("Max error: ",me)

print("----------------------------------------------")

vscore= explained_variance_score(y_test, y_pred)
print("Explained variance score: ",vscore)

print("----------------------------------------------")

rscore = r2_score(y_test, y_pred)
print("r2 score: ",rscore)

MSE: 175347467.16648313
----------------------------------------------
Mean absolute error:  3441.3880250546495
----------------------------------------------
Median absolute error:  1632.99
----------------------------------------------
Mean squared logarithmic error:  1.2081591312978834
----------------------------------------------
Max error:  839829.28
----------------------------------------------
Explained variance score:  -0.01689406188331133
----------------------------------------------
r2 score:  -0.017940920995550336

In [ ]:
print(model.score(X_train,y_train))
#print(model.score(X_test,y_test))

0.8447551652395998

## **Playing with Random Forest**


1. n_estimators

2. criterion{“mse”, “mae”}

3. max_depth

4. min_samples_split

5. bootstrap

6. n_jobs

7. min_samples_leaf

8. max_features

9. random_state

10. max_leaf_nodes

In [ ]:
model=RandomForestRegressor(n_estimators=150,max_depth=3,random_state = 20)
model.fit(X_train,y_train.values.ravel())
y_pred=model.predict(X_test)

In [ ]:
mse = mean_squared_error(y_test,y_pred)
print("MSE:",mse)

print("----------------------------------------------")

mae = mean_absolute_error(y_test, y_pred)
print("Mean absolute error: ",mae)

print("----------------------------------------------")

vscore= explained_variance_score(y_test, y_pred)
print("Explained variance score: ",vscore)

print("----------------------------------------------")

rscore = r2_score(y_test, y_pred)
print("r2 score: ",rscore)

MSE: 169668435.71750325
----------------------------------------------
Mean absolute error:  3108.9045902859207
----------------------------------------------
Explained variance score:  0.015056037733791605
----------------------------------------------
r2 score:  0.015027439465844838

In [ ]:
print(model.score(X_train,y_train))

0.1636944817653726

In [ ]:
model=RandomForestRegressor(n_estimators=100,min_samples_split=6,min_samples_leaf=3,random_state = 30)
model.fit(X_train,y_train.values.ravel())
y_pred=model.predict(X_test)

In [ ]:
mse = mean_squared_error(y_test,y_pred)
print("MSE:",mse)

print("----------------------------------------------")

mae = mean_absolute_error(y_test, y_pred)
print("Mean absolute error: ",mae)

print("----------------------------------------------")

vscore= explained_variance_score(y_test, y_pred)
print("Explained variance score: ",vscore)

print("----------------------------------------------")

rscore = r2_score(y_test, y_pred)
print("r2 score: ",rscore)

MSE: 170780491.7686216
----------------------------------------------
Mean absolute error:  3291.4645984850727
----------------------------------------------
Explained variance score:  0.00889119558568352
----------------------------------------------
r2 score:  0.008571644128924971

In [ ]:
print(model.score(X_train,y_train))

0.48456315703308395

# **Comparison**

### **(1) Linear regression**

In [ ]:
model = LinearRegression(fit_intercept=True)
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
mse = mean_squared_error(y_test,y_pred)
print("MSE:",mse)

print("----------------------------------------------")

mae = mean_absolute_error(y_test, y_pred)
print("Mean absolute error: ",mae)

print("----------------------------------------------")


vscore= explained_variance_score(y_test, y_pred)
print("Explained variance score: ",vscore)

print("----------------------------------------------")

rscore = r2_score(y_test, y_pred)
print("r2 score: ",rscore)

MSE: 169049754.660396
----------------------------------------------
Mean absolute error:  3095.9235328737177
----------------------------------------------
Explained variance score:  0.018654351580124073
----------------------------------------------
r2 score:  0.01861905544554021

### **(2) Polynomial Regression**

In [ ]:
polyreg=make_pipeline(PolynomialFeatures(2),LinearRegression())
polyreg.fit(X,y)

Pipeline(memory=None,
         steps=[('polynomialfeatures',
                 PolynomialFeatures(degree=2, include_bias=True,
                                    interaction_only=False, order='C')),
                ('linearregression',
                 LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
                                  normalize=False))],
         verbose=False)

In [ ]:
y_pred=polyreg.predict(X_test)

In [ ]:
mse = mean_squared_error(y_test,y_pred)
print("MSE:",mse)

print("----------------------------------------------")

mae = mean_absolute_error(y_test, y_pred)
print("Mean absolute error: ",mae)

print("----------------------------------------------")


vscore= explained_variance_score(y_test, y_pred)
print("Explained variance score: ",vscore)

print("----------------------------------------------")

rscore = r2_score(y_test, y_pred)
print("r2 score: ",rscore)

MSE: 144949891.4078527
----------------------------------------------
Mean absolute error:  3551.721288044392
----------------------------------------------
Explained variance score:  0.15852801509118541
----------------------------------------------
r2 score:  0.15852547891197488